### ISSUE TITLE
Refactor lava messaging and implement remaining PyPorts

### ISSUE THREAD

**Issue by mgkwill** [lava-nc/lava#12]
As a user I'd like to be able to use different ports based on sparsity using vectors and scalars. 

Implied ports:
- PyInPortVectorSparse
- PyInPortScalarDense
- PyInPortScalarSparse
- PyOutPortVectorSparse
- PyOutPortScalarDense
- PyOutPortScalarSparse

Retrofit to work with other input types/shapes:
- PyInPortVectorDense

https://github.com/lava-nc/lava/blob/9d80ea15af495b87df7f4b63e83531bdaf7d41f9/lava/magma/core/model/py/ports.py#L53-L75

Ensure that ports process data correctly when receiving from the matrix:

| | Vector | Vector | Scalar | Scalar |
| -----------| ------------- | -------- | ------- | ------- |
| -----------| -Receive- Dense | -Receive- Sparse | -Receive- Dense | -Receive- Sparse |
| Vec -Send- Dense  | ------- | ------- | ------- | ------- |
| Vec -Send- Sparse | -------  | ------- | ------- | ------- |
| Sca -Send- Dense  | ------- | ------- | ------- | ------- |
| Sca -Send- Sparse | -------  | ------- | ------- | ------- |

**Comment by joyeshmishra** [comment]
Closing this issue as discussed with Yash and Marcus. The necessary protocols implemented between Python Processes are just VecDense <-> VecDense and VecSparse <-> VecSparse. Python to C Processes can communication additionally for VecDense <-> SeqDense and VecSparse <-> SeqSparse. Other communication protocols are not supported due to lack of use cases.
