### ISSUE TITLE
Communication of special objects between process definiton and model definition

### ISSUE THREAD

**Issue by bamsumit** [lava-nc/lava#159]
Objective of issue:
To allow some specific objects communicated from _process_ definition to _model_ definition.

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

- At the moment, we can only communicate In/Out ports and Vars between process and models. In some cases it is useful to communicate other generic objects (at least for CPU only implementation). This is useful to create generic dataloader process.

**Expected behavior:**

porposed implementation skeleton
``` python
class Dataloader(AbstractProcess):
    def __init__(...):
        ...
        self.save_for_model(self.dataset)
        ...

...
@implements(proc=Dataloader, protocol=LoihiProtocol)
class PyDataLoader(AbstractProcessModel):
    def __init__(...):
        ...
        self.dataset = self.load_from_proc()
        ...

```

**Steps to reproduce:**

- NA

**Related code:**

```

```

**Other information:**

```

```

**Comment by bamsumit** [comment]
@awintel I am happy to look at it. Need pointers.

**Comment by awintel** [comment]
I've discussed a similar design already with Elvin last year. Seems like he implemented this more or less already.

Take a look at the 'proc_params' parameter in AbstractProcess. This is a dictionary you can set in the constructor.
The compiler will pass this attribute to the ProcessBuilder in line 342. 
In turn the ProcessBuilder will pass 'proc_params' to the ProcessModel after instantiation in line 363 in builder.py.

This should more or less accomplish what you want but could probably be improved:
1. Perhaps we need to make a deep copy of proc_params because the Builder and ProcModel will we deployed to  different system process or a different node entirely.
2. Perhaps we need to add an 'init' method to the PyProcModel for doing general initialization work before 'run' gets launched.
