### ISSUE TITLE
channel_utils looks out of date

### ISSUE THREAD

**Issue by DjangoFett** [lava-nc/lava#26]
https://github.com/lava-nc/lava/blob/main/lava/magma/compiler/channels/channel_utils.py
```
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier:  BSD-3-Clause
import numpy as np
from lava.magma.compiler.channels.pypychannel import __PyPyChannel


def __create_pypy_mgmt_channel(smm, name) -> __PyPyChannel:
    """
    Helper function to create a python to python Mgmt channel. This is typically
    backed by shared memory. Shared memory needs to be managed by the creator.
    :param smm: Shared Memory Manager
    :param name: Name of the Mgmt Channel. Only Mgmt Commands are sent on this.
    :return: __PyPyChannel Channel Handler
    """
    channel = __PyPyChannel(
        smm=smm, name=name, shape=(1,), dtype=np.int32, size=8
    )
    return channel
```

I was looking into improving the test coverage and noticed the function `__create_pypy_mgmt_channel` looks out of date.  There doesn't appear to be __PyPyChannel in the code base currently. Possibly the class has been renamed to `PyPyChannel` with a different `__init__` signature.

Without knowing the codebase well it seems like either  `__create_pypy_mgmt_channel` needs to be updated or deleted

**Comment by awintel** [comment]
Thanks for pointing this out!
Indeed, some renaming has happened here but apparently not completely. We are reworking some of this in the current sprint anyways so hopefully we'll get this fixed in the next release. 
@joyeshmishra Could you take a look?

As a next step, we want to separate the Runtime more cleanly from Python multiprocessing because ultimately we want to move away from it to enable true multi-node processing with Ray. 

If there's interest in this part of the code base by some developers, we should probably share our plans relating this part of the code base soon in another post...

**Comment by DjangoFett** [comment]
No problem! Is there a slack workspace (or some equivalent) for lava yet?

**Comment by awintel** [comment]
Not yet. We'll think about it!

For now, we continue to use Git issues and discussions.

**Comment by mgkwill** [comment]
Removing https://github.com/lava-nc/lava/blob/main/lava/magma/compiler/channels/channel_utils.py if it is needed later, 
 someone can add it back with the correct imports and usage.

See #37

**Comment by mgkwill** [comment]
@DjangoFett Thanks for finding this and opening an issue!
