### ISSUE TITLE
Inherit a process but still use same process model

### ISSUE THREAD

**Issue by epaxon** [lava-nc/lava#291]
Objective of issue:

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

- I want to inherit a process and add some functionality, but i still want to use same process model. 

**Expected behavior:**

- Compiler understands that process children can use parent process model

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by awintel** [comment]
This isn't possible at the moment.

If you inherit from a Process, you have created a new Process that could be incompatible with the ProcModels of the old Process.

How would the compiler know that you only modified the Proc in a compatible way?

Perhaps we could label the sub class in a way that it is compatible with ProcModels of the nearest super class. But then we've broken the design because Procs shouldn't be aware of their implementation. ProcModels specify which Procs they implement.
