### ISSUE TITLE
ValueError: Empty Module Name lif.run() when running Tutorial02

### ISSUE THREAD

**Issue by VieveF** [lava-nc/lava#326]
Objective of issue: lif.run() error for tutorial02, ValueError: Empty Module Name

**Lava version:**

- [ ] **0.5.0** (feature release)
- [ ] **0.4.1** (bug fixes)
- [x] **0.4.0** (current version)
- [ ] **0.3.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- I have a python script that runs tutorial02. I'm not using the jupyter notebook version. (I can see that there is a similar issue here:  #247 but it specifically uses the notebook version)
- When the script reaches lif.run command it exits with an error. The error is at this line:
`lif.run(condition=RunSteps(num_steps=1), run_cfg=Loihi1SimCfg())`

- Traceback:
```
Traceback (most recent call last):
  File "C:\Users\UserName\PycharmProjects\Lava_Tutorials\tutorial.py", line 22, in <module>
    lif.run(condition=RunSteps(num_steps=1), run_cfg=Loihi1SimCfg())  # gives errors here
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\site-packages\lava\magma\core\process\process.py", line 338, in run
    executable = self.compile(run_cfg, compile_config)
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\site-packages\lava\magma\core\process\process.py", line 364, in compile
    return compiler.compile(self, run_cfg)
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\site-packages\lava\magma\compiler\compiler.py", line 129, in compile
    proc_group_digraph = ProcGroupDiGraphs(process, run_cfg)
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\site-packages\lava\magma\compiler\compiler_graphs.py", line 607, in __init__
    proc_procmodel_map = ProcGroupDiGraphs._map_proc_to_model(proc_list,
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\site-packages\lava\magma\compiler\compiler_graphs.py", line 982, in _map_proc_to_model
    models_cls = ProcGroupDiGraphs._find_proc_models(proc=proc)
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\site-packages\lava\magma\compiler\compiler_graphs.py", line 807, in _find_proc_models
    parent_module = importlib.import_module(module_spec.parent)
  File "C:\ProgramData\Anaconda3\envs\Lava_Tutorials\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1047, in _gcd_import
  File "<frozen importlib._bootstrap>", line 981, in _sanity_check
ValueError: Empty module name
```

**Expected behavior:**

- It should run the simulation without error.

**Steps to reproduce:**

- I'm using lava with in a conda (4.13.0) environment (python3.10) in PyCharm CE. I installed lava using conda-forge. 
- I receive the same error and traceback on both Windows 10 Home and Ubuntu 20.04 with the same environment setup.
- The tutorial02 code is used as is but the Process and ProcessModel classes are imported into main from a separate script.

**Other information:**

- I can see there is a discussion at #95 for issues with tutorial02 using jupyter notebooks on Windows which may be related. I am getting this issue without the notebook and also on Ubuntu 20.04 as well. If it's an issue with my environment I have not yet been able to determine the cause.

**Comment by jacobpennington** [comment]
**Short version: importing processes and models from *installed* packages with full imports works, relative imports and importing from scripts in the same directory do not. Or at least, this was my experience with using the tutorials today.**

I ran into this same error, and was able to resolve it. In case the same steps were causing this for you (or some one else in the future), here's what I did to both cause and resolve the error:

1) Because of the Jupyter windows issue you mention, I had to put the class definitions in a separate .py file and import them to Jupyter. This was not a big concern for me since I would want to do that eventually anyway when implementing my own models.

2) Step 1 is essentially what caused the error for me. I was just importing from a standalone .py script in the same directory (e.g. `from tutorial2_stuff.py import LIF`). It looks like this breaks because Lava at some point relies on `importlib.util.find_spec`, which only finds modules in installed packages.

3) Attempted to fix the issue by setting up a minimal `lava-scripts` package to install and import from with `mylava/proc/processes.py` and `mylava/proc/models.py`. In this structure, I used a relative import when defining the process model (e.g. `from .processes import LIF`). At this point the `lif.run()` code was still raising an error, but a different one:
`NoProcessModelFound: No ProcessModels found that implement Process <...>`.

4) Replacing the relative import with a full import (e.g. `from mylava.proc.processes import LIF`) fixed the issue, and the tutorial code can now run without error. Apparently the `@implements` decorator can't parse relative imports into full ones (for later use by other code), I'm not sure if that's unintentional or due to some other limitation.


Hardware/OS notes: Windows 10, Intel 64bit processor, Lava v0.4.0 installed via conda v4.12.0.

**Comment by VieveF** [comment]
Thanks for your quick reply. I followed the steps you outlined above using a full import on a custom package and now it's working without an issue. Many thanks.

**Comment by PhilippPlank** [comment]
@jacobpennington Thank you for explaining the issue and showing a way to resolve it. 

We know that some aspects of the Lava environment (namespaces etc.) is currently not as easy to use as it should be, especially for Lava development. We are trying to improve it in the future.

Thank you for the issue, I will close it now. Feel free to open a new one if you encounter other obstacles :)
