### ISSUE TITLE
Execution time of `.read()` on a RefPort grows the more we call it

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#586]
**Describe the bug**
Execution time of `.read()` on a RefPort grows the more we call it.

**To reproduce current behavior**
1. When I run this code ...
```python
# Imports
import numpy as np
import time

from lava.magma.core.process.process import AbstractProcess
from lava.magma.core.process.ports.ports import RefPort
from lava.magma.core.process.variable import Var

from lava.magma.core.sync.protocols.loihi_protocol import LoihiProtocol
from lava.magma.core.model.py.ports import PyRefPort
from lava.magma.core.model.py.type import LavaPyType
from lava.magma.core.resources import CPU
from lava.magma.core.decorator import implements, requires
from lava.magma.core.model.py.model import PyLoihiProcessModel

from lava.magma.core.run_conditions import RunSteps
from lava.magma.core.run_configs import Loihi1SimCfg


# MyProcess Process
class MyProcess(AbstractProcess):
    def __init__(self):
        super().__init__()
        self.var = Var(shape=(10, 10), init=np.zeros((10, 10)))


# MyProcess ProcessModel
@implements(proc=MyProcess, protocol=LoihiProtocol)
@requires(CPU)
class MyProcessPM(PyLoihiProcessModel):
    var: np.ndarray = LavaPyType(np.ndarray, float)


# Reader Process
class Reader(AbstractProcess):
    def __init__(self):
        super().__init__()
        self.ref_port = RefPort(shape=(10, 10))


# Reader ProcessModel
@implements(proc=Reader, protocol=LoihiProtocol)
@requires(CPU)
class ReaderPM(PyLoihiProcessModel):
    ref_port: PyRefPort = LavaPyType(PyRefPort.VEC_DENSE, float)

    def post_guard(self):
        return True

    def run_post_mgmt(self):
        checkpoint_1 = time.perf_counter()
        self.ref_port.read()
        checkpoint_2 = time.perf_counter()
        print(checkpoint_2-checkpoint_1)


def main():
    # Params
    num_steps = 10000
    run_cnd = RunSteps(num_steps=num_steps)
    select_tag = "floating_pt"
    run_cfg = Loihi1SimCfg(select_tag=select_tag)

    # Instantiating Processes
    my_process = MyProcess()
    reader = Reader()

    # Connecting Processes
    reader.ref_port.connect_var(my_process.var)

    # Running
    my_process.run(condition=run_cnd, run_cfg=run_cfg)

    # Stopping
    my_process.stop()


if __name__ == "__main__":
    main()
```
2. I see that the printed values (execution time of `.read()` on the RefPort) grow as time passes.

**Expected behavior**
I would expect the average of the printed values to remain constant.
In other words, I expect the average of the execution time of `.read()` on the RefPort to remain constant.

**Screenshots**
Plotting the timeseries of the printed values, we get the following :

![Execution time - RefPort read](https://user-images.githubusercontent.com/36999864/214888795-122ea749-af35-4254-87b9-5479768ba75f.png)

We indeed see that the average (and standard deviation) of the execution time of `.read()` on the RefPort grows the more we call it.

**Environment (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Lava version 0.6.0

**Additional context**
This has major implications for Monitors, as they use RefPort to read values from Vars in other Processes, every time step.
This makes execution time grow extremely fast in networks involving Monitors.

**Comment by awintel** [comment]
Great analysis. Thanks for reporting.

I believe there was a similar issue reported before...

**Comment by tim-shea** [comment]
This issue seems to trace back to the __setattr__ function in lava.magma.core.py.model.AbstractPyProcessModel. This function incorrectly adds PyPorts and VarPorts to self.py_ports and self.var_ports, even when those ports are already present in the list. Adding a check to avoid this behavior results in a ~300x speedup after 2000 timesteps using the model @gkarray shared above.

![Figure_1](https://user-images.githubusercontent.com/2815912/233709890-bc6ad85a-1470-4571-bc17-fe2840c0cfcd.png)

**Comment by tim-shea** [comment]
Also adding this here in case anyone else finds it useful, and so I can find it in the future:

Tracking down the precise cause of this issue was pretty complicated for me, because the CSP structure makes it really hard to trace performance across channel, port, and subprocess hierarchies. Although I ultimately found the offending code by stepping a debugger very carefully, I first had to figure out where the increase in execution time was coming from, which I was able to do with CProfile and snakeviz.

If you want to *somewhat* easily generate a performance profile for each Subprocess (corresponding to a ProcessModel), you can replace target_fn on line 85 of runtime.py with the following:

```
def target_fn(*args, **kwargs):
    """
    Function to build and attach a system process to

    :param args: List Parameters to be passed onto the process
    :param kwargs: Dict Parameters to be passed onto the process
    :return: None
    """
    try:
        builder = kwargs.pop("builder")
        actor = builder.build()
        name = actor.__class__.__name__
        import cProfile
        cp = cProfile.Profile()
        cp.enable()
        actor.start(*args, **kwargs)
        cp.disable()
        cp.dump_stats(f'Performance_{name}.profile')
    except Exception as e:
        print("Encountered Fatal Exception: " + str(e))
        print("Traceback: ")
        print(traceback.format_exc())
        raise e
```

Then, after running your code, you should find a file named `Performance_<ProcessModelName>.profile` for each ProcessModel, which you can load in snakeviz or another visualization of your choice.
