### ISSUE TITLE
Remove legacy __init__.py code

### ISSUE THREAD

**Issue by mgkwill** [lava-nc/lava#64]
There are multiple places across lava and lava libs codebase that include explicate Namespace packages.

Such as:
https://github.com/lava-nc/lava/blob/cfcd72a7a3039cf8ba47b82d2f6e234fb004ab88/src/lava/__init__.py#L1
and:
https://github.com/lava-nc/lava/blob/cfcd72a7a3039cf8ba47b82d2f6e234fb004ab88/src/lava/magma/__init__.py#L1
and:
https://github.com/lava-nc/lava-optimization/blob/f7fce219b2b2978d210d9b5ffb5a8168967bf511/src/lava/__init__.py#L4-L8

However since python 3.3 Namespaces are defined implicitly:
[PEP 420 -- Implicit Namespace Packages](https://www.python.org/dev/peps/pep-0420/)

This issue involves
* Remove all legacy __init__.py code as defined in **PEP 420**
* Test the resulting Namespace and Package function
* If Namespace and Packages still function, open pull requests to remove legacy code

**Comment by awintel** [comment]
Yes, I think this was initially done intentionally by @srrisbud because removing all legacy init.py files is a bad thing. Removing the init.py gives you implicit names spaces but you also have no more chance to write a custom init.py to e.g. simplify imports.
Perhaps there is another way that I'm not aware of.
